[storage_nodes]
node1 ansible_host=10.0.1.11 node_port=7001
node2 ansible_host=10.0.1.12 node_port=7001
node3 ansible_host=10.0.1.13 node_port=7001

[coordinator]
coord1 ansible_host=10.0.1.10

[kvstore_cluster:children]
storage_nodes
coordinator
